[workspace]
members = ["world"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
typst = "0.13"
typst-assets = { version = "0.13", features = ["fonts"] }
typst-library = "0.13"
typst-render = "0.13"
typst-syntax = "0.13"
typst-utils = "0.13"

[package]
name = "discordyst"
version = "0.1.0"
edition.workspace = true
