app = 'typscord'
primary_region = 'sin'

[deploy]
strategy = 'bluegreen'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
method = 'GET'
path = '/'
grace_period = '5s'
interval = '30s'
timeout = '5s'

[[vm]]
size = 'shared-cpu-1x'
