# fly.toml app configuration file generated for typscord on 2025-09-22T17:01:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'typscord'
primary_region = 'sin'

[build]

[deploy]
  strategy = 'bluegreen'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
