[package]
name = "discordyst-interaction"
version = "0.1.0"
edition.workspace = true

[dependencies]
discordyst-http.workspace = true
serde_json = { version = "1", default-features = false }
twilight-http.workspace = true
twilight-model.workspace = true
